# Generated by Django 5.2.3 on 2025-06-20 06:37

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.core.management import call_command
from django.db import migrations, models


def run_backfill_command(apps, schema_editor):
    call_command('backfill_user_hashes')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHash',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='userhash', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hash', models.CharField(db_index=True, max_length=12, unique=True)),
            ],
            options={
                'db_table': 'userhash',
            },
        ),
        migrations.RunPython(run_backfill_command)
    ]
